[package]
name = "desktop-notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
zip = { workspace = true }
announcer = { path = "../announcer" }
dpp = "0"
