name: build-mod

on:
  workflow_dispatch:
  push:
    paths: ['packages/**']
  pull_request:
    paths: ['packages/**']

jobs:
  build-mod:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Deps
        run: bun install
      
      - name: Build
        run: bun -F @extendify/scripts build
      
      - name: Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: dist/
      
      - name: Update Release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload artifacts dist/* --clobber
